name = "Skia"
uuid = "d59498f3-381e-4841-a765-4609d464ae1b"
authors = ["Erik Stensmo "]
version = "0.1"

[deps]

[compat]
WiringPi_jll = "3.14.0"
julia = "1.9.4"


[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"


[targets]
test = ["Test"]
